# Generated by Django 4.1.2 on 2022-10-31 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('type', models.CharField(default='authors', max_length=255)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(blank=True, default='http://127.0.0.1:8001/', max_length=255)),
                ('displayName', models.CharField(blank=True, max_length=255, null=True)),
                ('github', models.URLField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('profileImage', models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
