# Generated by Django 4.1.2 on 2022-10-31 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='uuid',
            new_name='id',
        ),
    ]
